sudo: required
dist: trusty
language:
  - cpp
  - python
python:
  - "2.7"
compiler:
  - gcc
notifications:
  email:
    on_success: always
    on_failure: always
env:
  - ROS_DISTRO=indigo
script:
  - export CI_SOURCE_PATH=$(pwd)
  - export REPOSITORY_NAME=${PWD##*/}
  - if [ ! "$ROS_PARALLEL_JOBS" ]; then export ROS_PARALLEL_JOBS="-j8 -l8";  fi
  - echo "Testing branch $TRAVIS_BRANCH of $REPOSITORY_NAME"
  - sudo sh -c 'echo "deb http://packages.ros.org/ros-shadow-fixed/ubuntu `lsb_release -cs` main" > /etc/apt/sources.list.d/ros-latest.list'
  - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y python-catkin-pkg python-rosdep python-wstool python-catkin-tools ros-$ROS_DISTRO-catkin
  - sudo rosdep init
  - rosdep update; while [ $? != 0 ]; do sleep 1; rosdep update; done
  - mkdir -p ~/ros/ws_$REPOSITORY_NAME/src
  - cd ~/ros/ws_$REPOSITORY_NAME/src
  - ln -s $CI_SOURCE_PATH . # Link the repo we are testing to the new workspace
  - git clone https://github.com/ros/std_msgs           std_msgs
  - git clone https://github.com/ros/ros_comm_msgs      ros_comm_msgs   -b ${ROS_DISTRO}-devel
  - git clone https://github.com/ros/common_msgs        common_msgs     -b ${ROS_DISTRO}-devel
  - git clone https://github.com/ros/actionlib          actionlib       -b ${ROS_DISTRO}-devel
  - find actionlib  -name CMakeLists.txt  -exec sed -i 's@add_subdirectory(test)@#add_subdirectory(test)@' {} \;
  - cd ..
  - rosdep install -r -n --from-paths src --ignore-src --rosdistro $ROS_DISTRO -y
  - source /opt/ros/$ROS_DISTRO/setup.bash
  - catkin_make $ROS_PARALLEL_JOBS
  # test for roseus
  - sudo apt-get install -qq -y ros-${ROS_DISTRO}-roseus
  - sudo dpkg -r --force-depends ros-${ROS_DISTRO}-geneus
  # need to use latest test codes
  - rm -fr devel build src/*
  - cd src
  - git clone http://github.com/jsk-ros-pkg/jsk_roseus /tmp/jsk_roseus
  - cp -r /tmp/jsk_roseus/roseus ./
  #- sudo wget https://raw.githubusercontent.com/k-okada/jsk_roseus/fix_generate_all/roseus/scripts/generate-all-msg-srv.sh -O /opt/ros/hydro/share/roseus/scripts/generate-all-msg-srv.sh
  - ln -s $CI_SOURCE_PATH . # Link the repo we are testing to the new workspace
  - cd ..
  # check roseus
  - source /opt/ros/$ROS_DISTRO/setup.bash
  - catkin build
  - source devel/setup.bash
  - rostest roseus test-genmsg.catkin.test
  - rostest roseus test-genmsg-oneworkspace.catkin.launch
  # check pr2eus
  - git clone http://github.com/jsk-ros-pkg/jsk_pr2eus src/jsk_pr2eus
  - sudo apt-get -qq -f install
  - rosdep install -r -n --from-paths src --ignore-src --rosdistro $ROS_DISTRO -y
  - sudo dpkg -r --force-depends ros-hydro-geneus
  - catkin clean -a
  - source /opt/ros/$ROS_DISTRO/setup.bash
  - catkin build
  - source devel/setup.bash
  - rostest pr2eus pr2-ri-test-simple.launch
  - rostest pr2eus default-ri-test.launch
  - rostest pr2eus pr2eus-test.launch
after_failure:
  - rostest -t roseus test-genmsg.catkin.test
  - rostest -t roseus test-genmsg-oneworkspace.catkin.launch
